name: Test Action
on:
  push:
    branches: ["main"]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo hola mundo
      - name: Checkout
        uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 25
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm ci
      - run: pnpm run build
