name: TICS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - run: ls -la

      - name: hola erick
        run: echo "hola erick"
